name: Trigger auto deployment for container-app-her6ictcgnffq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-her6ictcgnffq-AutoDeployTrigger-cc65ea0b-1bc5-4786-b2e5-28559d1592ae.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPHER6ICTCGNFFQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPHER6ICTCGNFFQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPHER6ICTCGNFFQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPHER6ICTCGNFFQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPHER6ICTCGNFFQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-her6ictcgnffq
          resourceGroup: todolearn19468
          imageToBuild: default/container-app-her6ictcgnffq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


